# Generated by Django 3.2 on 2021-04-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_stockproduct_requested_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockrequest",
            options={
                "permissions": (("can_approve", "Can approve requests"),),
                "verbose_name": "Solicitud de Stock",
                "verbose_name_plural": "Solicitudes de Stock",
            },
        ),
    ]
