# Generated by Django 3.2.3 on 2021-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_uploaded_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="available_by_default",
            field=models.BooleanField(default=True),
        ),
    ]
