# Generated by Django 3.2.3 on 2021-05-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_auto_20210514_1403"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="available_by_default",
            field=models.BooleanField(default=True, verbose_name="Disponible al crear"),
        ),
    ]
