# Generated by Django 3.2.5 on 2021-09-01 01:31

import apps.products.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_initial_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.utils.get_upload_path, verbose_name='Imagen'),
        ),
    ]
