# Generated by Django 3.2.9 on 2021-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_product_uploaded_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="can_be_sold",
            field=models.BooleanField(
                default=False, verbose_name="¿Puede ser vendido?"
            ),
        ),
    ]
