# Generated by Django 3.2.13 on 2022-10-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_options'),
        ('products', '0012_alter_product_options_product_reserved_stock_and_more'),
    ]

    operations = [
    ]
