# Generated by Django 3.2.13 on 2022-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_auto_20221028_0831"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="keys_cost",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Precio en llaves HL"
            ),
        ),
    ]
