# Generated by Django 3.2.13 on 2024-10-14 20:28

import apps.products.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_product_keys_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrequest",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (0, "Cancelado"),
                    (1, "Creado"),
                    (2, "Aprobado"),
                    (3, "Anulado"),
                    (4, "Rechazado"),
                ],
                default=apps.products.workflows.StockTransactionWorkflow.Choices[
                    "CREATED"
                ],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
