# Generated by Django 3.2.13 on 2024-10-14 21:15

import config.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_stockrequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='forum_url',
            field=config.fields.CustomURLField(verbose_name='URL del post del foro'),
        ),
    ]
