# Generated by Django 3.2.13 on 2024-10-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_stockrequest_forum_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockrequest",
            options={
                "ordering": ("state", "-pk"),
                "permissions": (("can_approve", "Can approve requests"),),
                "verbose_name": "Solicitud de Stock",
                "verbose_name_plural": "Solicitudes de Stock",
            },
        ),
    ]
