# Generated by Django 3.2 on 2021-04-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="name",
            field=models.CharField(default="", max_length=128, verbose_name="Nombre"),
            preserve_default=False,
        ),
    ]
