# Generated by Django 3.2 on 2021-04-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_container_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="key",
        ),
        migrations.AddField(
            model_name="field",
            name="access_method",
            field=models.CharField(
                default="", max_length=128, unique=True, verbose_name="Nombre del Campo"
            ),
            preserve_default=False,
        ),
    ]
