# Generated by Django 3.2 on 2021-05-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_field_fieldset_form"),
    ]

    operations = [
        migrations.DeleteModel(name="Field",),
        migrations.DeleteModel(name="Fieldset",),
        migrations.DeleteModel(name="Form",),
    ]
