# Generated by Django 3.2.3 on 2021-06-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="accumulated_posts",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="posteos acumulados"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="salary_scale",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="escalafón laboral"
            ),
            preserve_default=False,
        ),
    ]
