# Generated by Django 3.2.3 on 2021-06-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_salary_scale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="vault",
        ),
        migrations.AddField(
            model_name="profile",
            name="vault_number",
            field=models.IntegerField(default=0, verbose_name="Número de Bóveda"),
            preserve_default=False,
        ),
    ]
