# Generated by Django 4.0.5 on 2022-06-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="boxroom_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de Bóveda Trastero"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="character_sheet",
            field=models.IntegerField(
                null=True, verbose_name="Número de Bóveda Trastero"
            ),
        ),
    ]
