# Generated by Django 4.0.5 on 2022-08-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_alter_profile_range_of_creatures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="galleons",
            field=models.IntegerField(default=0, verbose_name="Galeones"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="character_sheet",
            field=models.IntegerField(
                null=True, verbose_name="Número de Ficha de Personaje"
            ),
        ),
    ]
