# Generated by Django 3.2.13 on 2022-11-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_profile_galleons_alter_profile_character_sheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.URLField(max_length=512, null=True),
        ),
    ]
