# Generated by Django 3.2.13 on 2022-11-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="formatted_name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
