# Generated by Django 3.2.13 on 2025-04-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_profile_formatted_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_url",
            field=models.URLField(max_length=512, null=True),
        ),
    ]
