# Generated by Django 4.2.13 on 2025-05-07 22:27

import apps.profiles.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_profile_profile_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ("pk",),
                "permissions": (("can_sync", "Can sync profile data"),),
                "verbose_name": "Mago",
                "verbose_name_plural": "Magos",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(1, "Creado")],
                default=apps.profiles.workflows.ProfileWorkflow.Choices["CREATED"],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
