# Generated by Django 3.2.2 on 2021-05-09 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0002_alter_sale_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="buyer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="authentication.user",
                verbose_name="vendedor",
            ),
            preserve_default=False,
        ),
    ]
