# Generated by Django 3.2.5 on 2021-08-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_sale_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="vip_sale",
            field=models.BooleanField(
                default=False, verbose_name="Compra con llaves HL"
            ),
        ),
    ]
