# Generated by Django 3.2.9 on 2021-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_sale_vip_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_award",
            field=models.BooleanField(
                default=False, verbose_name="Premio de Gala (sin importar stock)"
            ),
        ),
    ]
