# Generated by Django 4.0.3 on 2022-03-21 03:50

import apps.sales.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_sale_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("can_send_to_payment", "Puede enviar la compra para pago")
                ],
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
        migrations.AddField(
            model_name="sale",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(0, "Cancelado"), (1, "Creado"), (2, "Pagado")],
                default=apps.sales.workflows.SaleWorkflow.Choices["PAY"],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
