# Generated by Django 4.0.4 on 2022-06-02 02:27

import apps.sales.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_alter_sale_options_sale_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(0, "Cancelado"), (1, "Creado"), (2, "Pagado")],
                default=apps.sales.workflows.SaleWorkflow.Choices["CREATED"],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
