# Generated by Django 3.2.13 on 2022-11-13 03:12

import apps.sales.transitions
import apps.sales.workflows
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0014_auto_20221028_0831"),
        ("profiles", "0012_profile_formatted_name"),
        ("sales", "0009_alter_sale_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleSale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "vip_sale",
                    models.BooleanField(
                        default=False, verbose_name="Compra con llaves HL"
                    ),
                ),
                (
                    "is_award",
                    models.BooleanField(
                        default=False,
                        verbose_name="Premio de Gala (sin importar stock)",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[(0, "Cancelado"), (1, "Borrador"), (2, "Generado")],
                        default=apps.sales.workflows.MultipleSaleWorkflow.Choices[
                            "DRAFT"
                        ],
                        protected=True,
                        verbose_name="estado",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vendedor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, apps.sales.transitions.MultipleSateTransitions),
        ),
        migrations.CreateModel(
            name="SaleMultipleSale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=True,
                        help_text="Este campo se utiliza para marcar una compra de libros de hechizos o consumibles. <br>Libros de Hechizos. Marcado = Se puede usar<br>Consumibles. Desmarcado = Consumible utilizado<br>Criaturas (Premios y/o Régimen Transitorio). Desmarcado = La criatura se encuentra en la reserva de animales<br>",
                        verbose_name="Disponible?",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_sales",
                        to="sales.multiplesale",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "sale")},
            },
        ),
        migrations.AddField(
            model_name="multiplesale",
            name="products",
            field=models.ManyToManyField(
                through="sales.SaleMultipleSale",
                to="products.Product",
                verbose_name="productos",
            ),
        ),
        migrations.AddField(
            model_name="multiplesale",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="profiles.profile",
                verbose_name="Comprador",
            ),
        ),
        migrations.AddField(
            model_name="multiplesale",
            name="sales",
            field=models.ManyToManyField(to="sales.Sale", verbose_name="ventas"),
        ),
    ]
