# Generated by Django 3.2.13 on 2022-11-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_auto_20221112_2212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salemultiplesale",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
        ),
    ]
