# Generated by Django 3.2.13 on 2022-11-27 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_alter_salemultiplesale_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multiplesale",
            name="is_award",
        ),
        migrations.RemoveField(
            model_name="multiplesale",
            name="vip_sale",
        ),
        migrations.AddField(
            model_name="salemultiplesale",
            name="is_award",
            field=models.BooleanField(
                default=False, verbose_name="Premio de Gala (sin importar stock)"
            ),
        ),
        migrations.AddField(
            model_name="salemultiplesale",
            name="vip_sale",
            field=models.BooleanField(
                default=False, verbose_name="Compra con llaves HL"
            ),
        ),
        migrations.AlterField(
            model_name="multiplesale",
            name="date",
            field=models.DateField(default=datetime.datetime.now, verbose_name="Fecha"),
        ),
    ]
