# Generated by Django 3.2.13 on 2022-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_auto_20221127_0755"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplesale",
            name="legend",
            field=models.CharField(
                default="las Compras realizadas en el Magic Mall",
                max_length=128,
                null=True,
            ),
        ),
    ]
