# Generated by Django 3.2.13 on 2022-11-27 13:52

import config.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0013_multiplesale_legend"),
    ]

    operations = [
        migrations.AddField(
            model_name="salemultiplesale",
            name="html",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="salemultiplesale",
            name="url",
            field=config.fields.CustomURLField(
                null=True, verbose_name="Link de la bóveda"
            ),
        ),
        migrations.AlterField(
            model_name="multiplesale",
            name="legend",
            field=models.CharField(
                default="las Compras realizadas en el Magic Mall",
                help_text="Se le informa que {{ legend }} el {{ fecha }}",
                max_length=128,
                null=True,
            ),
        ),
    ]
