# Generated by Django 3.2.13 on 2022-11-27 13:54

import config.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0014_auto_20221127_0852"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salemultiplesale",
            name="html",
        ),
        migrations.RemoveField(
            model_name="salemultiplesale",
            name="url",
        ),
        migrations.AddField(
            model_name="multiplesale",
            name="html",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="multiplesale",
            name="url",
            field=config.fields.CustomURLField(
                null=True, verbose_name="Link de la bóveda"
            ),
        ),
    ]
