services:
  db:
    image: postgres:14.8-alpine3.18
    volumes:
      - .docker/.volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - .docker/.volumes/pgadmin/pgadmin-data:/var/lib/pgadmin
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    volumes:
      - .:/app/
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - db
