# Generated by Django 3.2.5 on 2021-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="inscription",
            field=models.IntegerField(
                default=1, unique=True, verbose_name="Número de topic de inscripción"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="business",
            name="rol",
            field=models.IntegerField(
                default=1, unique=True, verbose_name="Número de topic de rol"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="family",
            name="inscription",
            field=models.IntegerField(
                default=1, unique=True, verbose_name="Número de topic de inscripción"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="family",
            name="rol",
            field=models.IntegerField(
                default=1, unique=True, verbose_name="Número de topic de rol"
            ),
            preserve_default=False,
        ),
    ]
