# Generated by Django 3.2.5 on 2021-07-11 18:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_accumulated_posts"),
        ("properties", "0002_auto_20210711_1054"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Nombre de la familia"
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="Contenido")),
                (
                    "vault",
                    models.IntegerField(unique=True, verbose_name="Número de bóveda"),
                ),
                (
                    "inscription",
                    models.IntegerField(
                        unique=True, verbose_name="Número de topic de inscripción"
                    ),
                ),
                (
                    "rol",
                    models.IntegerField(
                        unique=True, verbose_name="Número de topic de rol"
                    ),
                ),
                (
                    "property_type",
                    models.IntegerField(
                        choices=[(0, "Familia"), (1, "Negocio")],
                        verbose_name="Tipo de propiedad",
                    ),
                ),
                (
                    "owner",
                    models.ManyToManyField(
                        to="profiles.Profile", verbose_name="Propietarios/Patriarcas"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="family",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Business",
        ),
        migrations.DeleteModel(
            name="Family",
        ),
    ]
