# Generated by Django 3.2.5 on 2021-07-16 13:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210711_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
