# Generated by Django 3.2 on 2021-05-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fieldset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=128, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Sección del formulario",
                "verbose_name_plural": "Secciones del formulario",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=128, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Formulario",
                "verbose_name_plural": "Formularios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CharField", "Texto"),
                            ("EmailField", "Correo"),
                            ("FileField", "Archivo"),
                            ("CharField:HiddenInput", "Campo Oculto"),
                            ("CharField:Textarea", "Cuadro de Texto"),
                            ("IntegerField:NumberInput", "Numero Enteros"),
                            ("CharField:NumberInput", "Numero Decimal"),
                            ("CharField:DateInput", "Fecha"),
                            ("ChoiceField", "Selector"),
                            ("MyChoiceField:MySelect2Widget", "Select2 Model"),
                            ("ChoiceField:RadioSelect", "RadioMultiple"),
                            (
                                "MultipleChoiceField:CheckboxSelectMultiple",
                                "CheckboxMultiple",
                            ),
                            ("BooleanField", "Estado"),
                        ],
                        max_length=64,
                        verbose_name="Tipo de campo",
                    ),
                ),
                ("label", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256, null=True)),
                ("widget", models.TextField(blank=True, null=True)),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="Es requerido?"),
                ),
                (
                    "fieldset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dynamicforms.fieldset",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_form",
                        to="dynamicforms.form",
                        verbose_name="Formulario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo",
                "verbose_name_plural": "Campos",
                "ordering": ["form", "fieldset", "pk"],
                "unique_together": {("form", "label")},
            },
        ),
    ]
