# Generated by Django 3.2.2 on 2021-05-13 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dynamicforms", "0002_auditapi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditapi", options={"ordering": ("-created_date",)},
        ),
        migrations.AlterField(
            model_name="field",
            name="type",
            field=models.CharField(
                choices=[
                    ("CharField:TextInput", "Texto"),
                    ("EmailField", "Correo"),
                    ("FileField", "Archivo"),
                    ("CharField:HiddenInput", "Campo Oculto"),
                    ("CharField:Textarea", "Cuadro de Texto"),
                    ("IntegerField:NumberInput", "Numero Enteros"),
                    ("CharField:NumberInput", "Numero Decimal"),
                    ("CharField:DateInput", "Fecha"),
                    ("ChoiceField", "Selector"),
                    ("MyChoiceField:MySelect2Widget", "Select2 Model"),
                    ("ChoiceField:RadioSelect", "RadioMultiple"),
                    ("MultipleChoiceField:CheckboxSelectMultiple", "CheckboxMultiple"),
                    ("BooleanField", "Estado"),
                ],
                max_length=64,
                verbose_name="Tipo de campo",
            ),
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=256, verbose_name="nombre")),
                ("path", models.CharField(max_length=256, verbose_name="url")),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dynamicforms.form",
                        verbose_name="formulario",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
