# Generated by Django 3.2.3 on 2021-05-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dynamicforms", "0003_auto_20210512_2136"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="action",
            options={"verbose_name": "Acción", "verbose_name_plural": "Acciones"},
        ),
    ]
