# Generated by Django 3.2.3 on 2021-05-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamicforms", "0005_alter_action_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="message",
            field=models.CharField(
                default="", max_length=32, verbose_name="Texto del Botón"
            ),
            preserve_default=False,
        ),
    ]
