# Generated by Django 3.2.3 on 2021-05-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamicforms", "0006_action_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="show_modal",
            field=models.BooleanField(default=False, verbose_name="¿Mostrar modal?"),
        ),
    ]
