# Generated by Django 3.2.3 on 2021-05-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamicforms", "0007_action_show_modal"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="super_admin_required",
            field=models.BooleanField(
                default=False, verbose_name="¿Es requerido ser administrador?"
            ),
        ),
    ]
