# Generated by Django 3.2.13 on 2025-04-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_topicapi"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicapi",
            name="description",
            field=models.CharField(
                default="",
                max_length=128,
                verbose_name="Detalle de donde se usará el id",
            ),
        ),
    ]
