# Generated by Django 3.2.13 on 2022-11-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "categoría", "verbose_name_plural": "categorías"},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "topic", "verbose_name_plural": "topics"},
        ),
    ]
