# Generated by Django 3.2.13 on 2022-11-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dices", "0003_roll_post_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dice",
            options={
                "verbose_name": "Dado predefinido",
                "verbose_name_plural": "Dados predefinidos",
            },
        ),
        migrations.AddField(
            model_name="dice",
            name="configuration",
            field=models.JSONField(default=dict, verbose_name="Configuración"),
        ),
    ]
