# Generated by Django 3.2.13 on 2022-11-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dices", "0004_auto_20221106_1503"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={
                "verbose_name": "topic",
                "verbose_name_plural": "topics para dados",
            },
        ),
    ]
