# Generated by Django 3.2.13 on 2024-10-20 20:02

import apps.dices.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("dices", "0005_alter_topic_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(0, "Cerrado"), (2, "Abierto")],
                default=apps.dices.workflows.TopicWorkflow.Choices["OPEN"],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
