# Generated by Django 3.2.13 on 2024-10-21 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dices", "0008_alter_topic_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="permissions",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Usuarios habilitados"
            ),
        ),
    ]
