# Generated by Django 3.2.13 on 2024-10-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dices", "0011_alter_topic_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="dice",
            name="categories",
            field=models.ManyToManyField(
                help_text="Selecciona una o más categorías para este dado",
                to="dices.Category",
                verbose_name="Categorias",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="allow_custom",
            field=models.BooleanField(
                default=True, verbose_name="Permitir dados personalizados"
            ),
        ),
    ]
