# Generated by Django 3.2.13 on 2024-10-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dices', '0012_auto_20241021_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nombre del dado'),
        ),
    ]
