# Generated by Django 3.2.13 on 2024-10-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dices", "0014_road"),
    ]

    operations = [
        migrations.AddField(
            model_name="roll",
            name="numeric_result",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="road",
            name="message",
            field=models.CharField(
                help_text="Puedes utilizar las siguientes variables: {{result}}, {{username}}",
                max_length=128,
                verbose_name="Mensaje",
            ),
        ),
        migrations.AlterField(
            model_name="road",
            name="result",
            field=models.IntegerField(verbose_name="Resultado"),
        ),
    ]
