# Generated by Django 3.2.13 on 2024-10-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dices", "0015_auto_20241028_1716"),
    ]

    operations = [
        migrations.AddField(
            model_name="roll",
            name="road_message",
            field=models.TextField(null=True),
        ),
    ]
