# Generated by Django 3.2.13 on 2025-01-13 17:01

import apps.dices.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("dices", "0016_roll_road_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={
                "permissions": (
                    ("can_manage", "Can manage dices"),
                    ("can_show_hidden", "Can show hidden"),
                ),
                "verbose_name": "topic",
                "verbose_name_plural": "topics para dados",
            },
        ),
        migrations.AlterField(
            model_name="topic",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(0, "Cerrado"), (1, "Abierto"), (2, "Oculto")],
                default=apps.dices.workflows.TopicWorkflow.Choices["OPEN"],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
