# Generated by Django 4.2.13 on 2025-05-07 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dices", "0017_auto_20250113_1201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Si no seleccionas ningún usuarios, todos podrán lanzar dados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuarios habilitados",
            ),
        ),
    ]
