# Generated by Django 3.2.3 on 2021-06-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_monthpayment_monthpaymentline"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthpaymentline",
            name="number_of_posts",
            field=models.IntegerField(default=0, verbose_name="Número de Posteos"),
        ),
        migrations.AlterField(
            model_name="monthpaymentline",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="payments.work",
                verbose_name="Usuario",
            ),
        ),
    ]
