# Generated by Django 3.2.3 on 2021-06-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_auto_20210601_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthpaymentline",
            name="paid",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="¿Pagado?"
            ),
        ),
        migrations.AlterField(
            model_name="monthpaymentline",
            name="month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="payments.monthpayment",
                verbose_name="Mes y año",
            ),
        ),
    ]
