# Generated by Django 3.2.3 on 2021-06-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_monthpaymentline_calculated_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthpaymentline",
            name="paid_url",
            field=models.URLField(
                blank=True, editable=False, null=True, verbose_name="Link del pago"
            ),
        ),
    ]
