# Generated by Django 3.2.3 on 2021-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_monthpaymentline_paid_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="work_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción del trabajo"
            ),
        ),
    ]
