# Generated by Django 3.2.5 on 2021-07-11 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_auto_20210711_1038"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertiesPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "month",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Mes y año"
                    ),
                ),
                (
                    "payment_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Familia"), (1, "Negocio")],
                        verbose_name="Tipo de pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago a Familias y Negocios",
                "verbose_name_plural": "Pagos a Familias y Negocios",
            },
        ),
    ]
