# Generated by Django 3.2.5 on 2021-07-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_propertiespayment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PropertiesPayment",
            new_name="PropertyPayment",
        ),
    ]
