# Generated by Django 3.2.5 on 2021-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_propertypaymentline_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertypaymentline",
            name="paid_url",
            field=models.URLField(editable=False, null=True),
        ),
    ]
