# Generated by Django 3.2.5 on 2021-08-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_monthpayment_payment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monthpayment",
            old_name="payment_post",
            new_name="post_url",
        ),
    ]
