# Generated by Django 3.2.5 on 2021-08-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_rename_payment_post_monthpayment_post_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertypaymentline",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="payments.propertypayment",
                verbose_name="Pago",
            ),
        ),
    ]
