# Generated by Django 3.2.5 on 2021-09-01 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_profile_avatar"),
        ("payments", "0018_alter_propertypaymentline_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="wizard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
                unique=True,
                verbose_name="Usuario",
            ),
        ),
    ]
