# Generated by Django 3.2.5 on 2021-09-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_alter_work_wizard"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthpaymentline",
            name="posts",
            field=models.JSONField(default={}),
        ),
    ]
