# Generated by Django 3.2.5 on 2021-09-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0021_auto_20210917_2155"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="parse_content",
            field=models.JSONField(default={}, verbose_name="contenido parseado"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.JSONField(default={}, verbose_name="contenido"),
        ),
    ]
