# Generated by Django 3.2.7 on 2021-09-18 21:46

import apps.payments.workflows
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0022_auto_20210918_1414"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(0, "Cancelado"), (1, "Creado"), (2, "Cargado")],
                default=apps.payments.workflows.PostWorkflow.Choices["CREATED"],
                protected=True,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.JSONField(default=dict, verbose_name="contenido"),
        ),
        migrations.AlterField(
            model_name="post",
            name="parse_content",
            field=models.JSONField(default=dict, verbose_name="contenido parseado"),
        ),
    ]
