# Generated by Django 3.2.9 on 2021-11-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0024_auto_20211114_1030"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Pago", "verbose_name_plural": "Pagos"},
        ),
        migrations.AddField(
            model_name="payment",
            name="url",
            field=models.URLField(
                blank=True, editable=False, null=True, verbose_name="url"
            ),
        ),
        migrations.AddField(
            model_name="paymentline",
            name="short_link",
            field=models.URLField(
                blank=True, editable=False, null=True, verbose_name="short url"
            ),
        ),
        migrations.AlterField(
            model_name="paymentline",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="payments.payment",
                verbose_name="Pago",
            ),
        ),
    ]
