# Generated by Django 4.0.4 on 2022-05-03 19:37

import config.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='url',
            field=config.fields.CustomURLField(blank=True, editable=False, null=True, verbose_name='url'),
        ),
    ]
