# Generated by Django 3.2.13 on 2022-12-05 02:06

import apps.payments.workflows
import config.fields
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0032_payment_reason_alter_payment_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthpayment",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (0, "Cancelado"),
                    (1, "Creado"),
                    (2, "Calculado"),
                    (3, "Pagado"),
                ],
                default=apps.payments.workflows.MonthlyPaymentWorkflow.Choices[
                    "CREATED"
                ],
                protected=True,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="monthpayment",
            name="post_url",
            field=config.fields.CustomURLField(
                blank=True, null=True, verbose_name="Link del pedido de pago"
            ),
        ),
    ]
