# Generated by Django 3.2.13 on 2022-12-05 02:09

import apps.payments.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0033_auto_20221204_2106"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthpaymentline",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (0, "Cancelado"),
                    (1, "Creado"),
                    (2, "Calculado"),
                    (3, "Pagado"),
                ],
                default=apps.payments.workflows.MonthlyPaymentWorkflow.Choices[
                    "CREATED"
                ],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
