# Generated by Django 3.2.13 on 2024-10-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0035_auto_20221208_0026"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthpayment",
            options={
                "ordering": ("-pk",),
                "verbose_name": "Pago CMI",
                "verbose_name_plural": "Pagos CMI",
            },
        ),
    ]
