# Generated by Django 3.2.13 on 2025-04-17 23:17

import apps.payments.transitions
import apps.payments.workflows
import config.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_profile_profile_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0036_alter_monthpayment_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "request_html",
                    models.TextField(null=True, verbose_name="HTML de la solicitud"),
                ),
                (
                    "vault_html",
                    models.TextField(null=True, verbose_name="HTML de la bóveda"),
                ),
                (
                    "request_url",
                    config.fields.CustomURLField(
                        null=True, verbose_name="Link a solicitud"
                    ),
                ),
                (
                    "vault_discount_url",
                    config.fields.CustomURLField(
                        null=True, verbose_name="Link al descuento"
                    ),
                ),
                (
                    "confirm_date",
                    models.DateTimeField(
                        null=True, verbose_name="Fecha de confirmación"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (0, "Cancelado"),
                            (1, "Creado"),
                            (2, "Confirmado"),
                            (3, "Aprobado"),
                            (4, "Rechazada"),
                        ],
                        default=apps.payments.workflows.DonationWorkflow.Choices[
                            "CREATED"
                        ],
                        protected=True,
                        verbose_name="estado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donación",
                "verbose_name_plural": "Donaciones",
                "permissions": (
                    ("can_approve_donation", "Can approve donations"),
                    ("can_reject_donation", "Can reject donations"),
                ),
            },
            bases=(models.Model, apps.payments.transitions.DonationTransitions),
        ),
        migrations.CreateModel(
            name="DonationLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "quantity",
                    models.PositiveBigIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4000),
                        ],
                        verbose_name="cantidad",
                    ),
                ),
                (
                    "vault_html",
                    models.TextField(null=True, verbose_name="HTML de la bóveda"),
                ),
                (
                    "vault_deposit_url",
                    config.fields.CustomURLField(
                        null=True, verbose_name="Link al depósito"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="--", max_length=128, verbose_name="motivo"
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donation_lines",
                        to="profiles.profile",
                        verbose_name="Beneficiario",
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="payments.donation",
                        verbose_name="Donación",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
