# Generated by Django 3.2.13 on 2024-11-14 17:24

import apps.management.transitions
import apps.management.workflows
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0012_profile_formatted_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (1, "Borrador"),
                            (3, "Completado"),
                        ],
                        default=apps.management.workflows.UpdateLevelWorkflow.Choices[
                            "DRAFT"
                        ],
                        protected=True,
                        verbose_name="estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualización de Niveles",
                "verbose_name_plural": "Actualizaciones de Niveles",
                "ordering": ["-id"],
                "abstract": False,
            },
            bases=(models.Model, apps.management.transitions.LevelUpdateTransitions),
        ),
        migrations.CreateModel(
            name="LevelUpdateLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "state",
                    models.IntegerField(
                        choices=[(1, "Borrador"), (2, "Completado")], default=1
                    ),
                ),
                ("content", models.JSONField()),
                (
                    "level_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="management.levelupdate",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_lines",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
