# Generated by Django 3.2.13 on 2024-11-18 01:18

import apps.management.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelupdateline",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[
                    (1, "Borrador"),
                    (2, "Completado"),
                ],
                default=apps.management.workflows.UpdateLevelWorkflow.Choices["DRAFT"],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
