# Generated by Django 3.2.13 on 2024-11-25 01:37

import apps.management.workflows
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_levelupdateline_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="levelupdateline",
            name="calculated_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="levelupdateline",
            name="calculated_social_rank",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="levelupdate",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(1, "Borrador"), (2, "Completado")],
                default=apps.management.workflows.UpdateLevelWorkflow.Choices["DRAFT"],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
