# Generated by Django 3.2.13 on 2025-02-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_auto_20241124_2037"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="levelupdate",
            options={
                "ordering": ["-id"],
                "permissions": (("can_update_levels", "Can update levels"),),
                "verbose_name": "Actualización de Niveles",
                "verbose_name_plural": "Actualizaciones de Niveles",
            },
        ),
    ]
