# Generated by Django 3.2.13 on 2025-02-06 17:10

import apps.management.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_levelupdateline_old_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelupdateline",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(1, "Borrador"), (2, "Completado"), (3, "Completado")],
                default=apps.management.workflows.UpdateLevelLineWorkflow.Choices[
                    "DRAFT"
                ],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
