# Generated by Django 3.2.13 on 2025-02-06 17:16

import apps.management.workflows
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_alter_levelupdateline_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelupdate",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(1, "En curso"), (2, "Completado")],
                default=apps.management.workflows.UpdateLevelWorkflow.Choices["DRAFT"],
                protected=True,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="levelupdateline",
            name="state",
            field=django_fsm.FSMIntegerField(
                choices=[(1, "En curso"), (2, "Completado"), (3, "Completado")],
                default=apps.management.workflows.UpdateLevelLineWorkflow.Choices[
                    "DRAFT"
                ],
                protected=True,
                verbose_name="estado",
            ),
        ),
    ]
