# Generated by Django 4.2.13 on 2025-05-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_alter_profile_options_profile_state"),
        ("management", "0007_auto_20250206_1216"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("forum_user_id", models.IntegerField()),
                ("original_data", models.JSONField()),
                ("new_data", models.JSONField()),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualización de Perfil",
                "verbose_name_plural": "Actualizaciones de Perfil",
                "ordering": ["-id"],
                "permissions": (("can_update_profiles", "Can update profiles"),),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["forum_user_id"], name="management__forum_u_474f98_idx"
                    )
                ],
            },
        ),
    ]
