# Generated by Django 4.2.13 on 2025-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_profilehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "type",
                    models.CharField(
                        choices=[("topic", "Topic"), ("post", "Post")], max_length=8
                    ),
                ),
                ("entry_id", models.IntegerField()),
                ("original_data", models.JSONField()),
                ("new_data", models.JSONField()),
            ],
            options={
                "verbose_name": "Actualización de topic y post",
                "verbose_name_plural": "Actualizaciones de topics",
                "permissions": (("can_update_entries", "Can update entries"),),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["entry_id", "type"],
                        name="management__entry_i_92f70f_idx",
                    )
                ],
            },
        ),
    ]
