# Generated by Django 4.0.5 on 2022-08-16 05:44

import apps.authentication.transitions
import apps.authentication.workflows
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="forum_user_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID del foro"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_moderator",
            field=models.BooleanField(default=False, verbose_name="Es moderador"),
        ),
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[(0, "Cancelado"), (1, "Enviado")],
                        default=apps.authentication.workflows.UserTokenWorkflow.Choices[
                            "SEND"
                        ],
                        protected=True,
                        verbose_name="estado",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de acceso",
                "verbose_name_plural": "Tokens de acceso",
                "abstract": False,
            },
            bases=(models.Model, apps.authentication.transitions.UserTokenTransitions),
        ),
    ]
