# Generated by Django 4.0.5 on 2022-08-16 05:44

import apps.ecommerce.transitions
import apps.ecommerce.workflows
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0009_alter_sale_state"),
        ("products", "0012_alter_product_options_product_reserved_stock_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "state",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (0, "Cancelado"),
                            (1, "Creado"),
                            (2, "Confirmado"),
                            (3, "Aprobado"),
                            (4, "Rechazada"),
                        ],
                        default=apps.ecommerce.workflows.PurchaseWorkflow.Choices[
                            "CREATED"
                        ],
                        protected=True,
                        verbose_name="estado",
                    ),
                ),
                ("html", models.TextField(null=True, verbose_name="HTML")),
                (
                    "boxroom_html",
                    models.TextField(null=True, verbose_name="HTML trastero"),
                ),
                (
                    "sales",
                    models.ManyToManyField(to="sales.sale", verbose_name="Ventas"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "permissions": (
                    ("can_approve", "Can approve purchases"),
                    ("can_reject", "Can reject purchases"),
                ),
            },
            bases=(models.Model, apps.ecommerce.transitions.PurchaseTransitions),
        ),
        migrations.CreateModel(
            name="PurchaseLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "created_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última fecha de modificación"
                    ),
                ),
                (
                    "modified_user",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="modificado por",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_lines",
                        to="products.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="ecommerce.purchase",
                        verbose_name="Compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea de compra",
                "verbose_name_plural": "líneas de compra",
                "unique_together": {("product", "purchase")},
            },
        ),
    ]
