# Generated by Django 4.1 on 2022-08-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="confirm_date",
            field=models.DateTimeField(null=True, verbose_name="Fecha de confirmación"),
        ),
    ]
