# Generated by Django 3.2.13 on 2022-10-29 15:15

import config.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_purchase_confirm_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="certification_url",
            field=config.fields.CustomURLField(
                null=True, verbose_name="Link de la certificación"
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="discount_url",
            field=config.fields.CustomURLField(
                null=True, verbose_name="Link al descuento en la bóveda"
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="purchase_url",
            field=config.fields.CustomURLField(
                null=True, verbose_name="Link de la compra en el foro"
            ),
        ),
    ]
